language: groovy

jdk:
- oraclejdk7

env:
- GRAILS_VERSION=2.2.4

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

script: grails refresh-dependencies && grails clean && grails upgrade --non-interactive && grails war --non-interactive

deploy:
  provider: releases
  api-key: "15116853a7ec2b2ba04f9ee612f05941ee9b36d4"
  file: "target/rockstar-1.0.0.war"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar
