language: groovy

jdk:
- oraclejdk7

env:
- GRAILS_VERSION=2.2.4

before_install:
- gvm install grails $GRAILS_VERSION || true

branches:
only:
- master

script: grails clean && grails upgrade --non-interactive && grails test-app --non-interactive && grails war --non-interactive
