sudo: false
cache:
  directories:
  - $HOME/.gradle/wrapper
language: groovy
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
jdk:
  - oraclejdk8
before_install:
- chmod 775 ./gradlew

script: ./gradlew check assemble --refresh-dependencies -Dgrails.env=prod
after_failure: ./travis/junit-errors-to-stdout.sh

deploy:
  provider: releases
  api-key: "15116853a7ec2b2ba04f9ee612f05941ee9b36d4"
  file: "target/rockstar-1.0.2.war"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar
