language: groovy

jdk:
- oraclejdk7

env:
- GRAILS_VERSION=2.2.4

before_install:
- gvm install grails $GRAILS_VERSION || true

branches:
only:
- master

script: ./grailsw refresh-dependencies && ./grailsw clean && ./grailsw upgrade --non-interactive && ./grailsw test-app --non-interactive && ./grailsw war --non-interactive
