sudo: false
cache:
  directories:
  - $HOME/.gradle/wrapper
language: groovy
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - secure= hRCMn9QCDVOvdkc6fhIr97itAvb02cB86hVjAAScDQDlH9i0ru+xTCsVcLsMQ1Db7a1dWFj28qnyvz+kqqevAr8W29ADaD2BVsMfCtO6LALMtyfTgPNXw0RHqQu4+LVj148mXwtsbefLhAB1aanKb8Wf1L/wguQBCqVN65V+58c=
jdk:
  - oraclejdk8
before_install:
- chmod 775 ./gradlew

script: ./gradlew check assemble --refresh-dependencies -Dgrails.env=prod
after_failure: ./travis/junit-errors-to-stdout.sh

deploy:
  provider: releases
  file: "build/libs/rockstar-1.0.2.war"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar
