email:
    host: mailhost.fyi.sas.com

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: "com.mysql.jdbc.Driver"
    username: admin
    password: admin

environments:
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3309/game?autoReconnect=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
